name: Invitationlabel
on:
  issue_comment:
    types: [labeled]

jobs:
  build:
    if:  github.event.label.name == 'approved'
    name: Add collaborator!
    runs-on: ubuntu-latest
    steps:
      - uses: derek-botany/invitation@main
        name: Perform invitation action
        env:
          # REQUIRED
          INVITATION_TOKEN: ${{ secrets.INVITE_COLLABORATORS }}
          # OPTIONAL
          ORG: false
